#!/bin/bash
# Modified options from https://github.com/JAremko/docker-x11-bridge
TMPDIR=/tmp/spacemacs-mmap xpra $XPRA_MODE $DISPLAY\
  --tcp-auth=none\
  --bind-tcp="0.0.0.0:${XPRA_TCP_PORT}"\
  --compress="${XPRA_COMPRESS}"\
  --dpi="${XPRA_DPI}"\
  --encoding="${XPRA_ENCODING}"\
  --html="${XPRA_HTML}"\
  --keyboard-sync="${XPRA_KEYBOARD_SYNC}"\
  --microphone=no\
  --mmap="${XPRA_MMAP}"\
  --no-daemon\
  --printing=no\
  --pulseaudio=no\
  --readonly="${XPRA_READONLY}"\
  --sharing="${XPRA_SHARING}"\
  --speaker=no\
  --start-child="xhost +"\
  --webcam=no
